name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PYTHON_DEFAULT_VERSION: "3.11"

jobs:
  test-linux-bundle:
    runs-on: ubuntu-latest
    container:
      image: "python:3.11"  # can not use ${{ env.PYTHON_DEFAULT_VERSION }} here
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install patchelf
          python -m pip install --upgrade nox pip setuptools
          git config --global --add safe.directory '*'
      - name: Bundle the distribution
        id: bundle
        run: SETUPTOOLS_SCM_DEBUG=1 nox -vs bundle
      - name: Info printing
        if: always()
        run: |
          git --version
          git status
          git describe
  test-macos-and-windows-bundle:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, windows-2019]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
      - name: Install dependencies
        run: python -m pip install --upgrade nox pip setuptools
      - name: Bundle the distribution
        id: bundle
        shell: bash
        run: nox -vs bundle
      - name: Info printing
        if: always()
        run: |
          git --version
          git status
          git describe
